# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moarctl < Formula
  desc "Cli app to for working with moar registry"
  homepage "https://github.com/dotindustries/homebrew-tap"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dotindustries/moar/releases/download/0.6.0/moarctl_0.6.0_Darwin_arm64.tar.gz"
      sha256 "55d8809a64420c8e93e48317231f5b59fa50202a4e8b3c3c325617479b88dbd0"

      def install
        bin.install "moarctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dotindustries/moar/releases/download/0.6.0/moarctl_0.6.0_Darwin_x86_64.tar.gz"
      sha256 "95ca7f0db71bfa8b3354ad8ed4a24c58764158fab31b39affc4b636dca63f28b"

      def install
        bin.install "moarctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dotindustries/moar/releases/download/0.6.0/moarctl_0.6.0_Linux_x86_64.tar.gz"
      sha256 "d75ad8213a36d336d5214b945f02a55aec6af2beec3b75f2f2e59ad2228e1b4c"

      def install
        bin.install "moarctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dotindustries/moar/releases/download/0.6.0/moarctl_0.6.0_Linux_arm64.tar.gz"
      sha256 "41db8f96daef6d88ac33e39a9b13224deef8f5442b266401fcc69ad01d81f7ae"

      def install
        bin.install "moarctl"
      end
    end
  end
end
